

services:
  backend:
    build: ./backend
    container_name: skillswap_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillswap
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env:ro

  db:
    image: postgres:15
    container_name: skillswap_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillswap
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  dbdata:
